Task 7-1
asviel/made-2019-fall-algo pull request #3
Opened 2019-11-16 21:41 UTC by asviel

Я не успел отправить посылку в Яндекс.Контест до дедлайна(

2019-11-21 08:01 UTC, smatskevich requested changes
И еще падает на одном из первых тестов:

Тест tests/002
Ввод
15
1 41
1 18467
2 0
1 26500
1 19169
2 1
1 11478
1 29358
2 2
1 24464
1 5705
2 0
1 23281
1 16827
2 1

Вывод
0
0
0
1
3
0
2
6

Ответ
0 0 0 1 1 0 2 3 2 3 

Сообщение чекера
Completion status: ABNORMAL_EXIT
Term sig: SEGV
Error code: null

2019-11-21 08:01 UTC, smatskevich commented on hw03/task7_1.cpp
> +    TreapNode* t1 = new TreapNode();
Выделенные узлы не нужны - они пропадут. Проинициализируйте нулями.

2019-11-30 22:27 UTC, asviel commented
Инициализировал деревья под Split nullptr, исправил ошибку (забыл менять текущее значение порядковой статистики при поиске узла для удаления).

2019-11-30 22:35 UTC, asviel commented
Еще возврашал значение вместо ключа для удаления по ключу), и неправильно искал удаление по value (надо по число солдат (root_->value) - value - 1, потому что все инвертировано по построению

2019-12-04 00:42 UTC, smatskevich approved these changes
Тесты пройдены.
Принято.

2019-12-15 16:58 UTC, merged